# workflowì˜ ì´ë¦„
name: Run Test

on:
    # develop ë¸Œëœì¹˜ì— pushë‚˜ pull_request ì´ë²¤íŠ¸ê°€ ì¼ì–´ë‚˜ë©´ í•´ë‹¹ workflowë¥¼ ì‹¤í–‰
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        
# workflowì˜ ì‹¤í–‰ì€ í•˜ë‚˜ ì´ìƒì˜ jobìœ¼ë¡œ êµ¬ì„±ë¨
jobs:
    # 'build'ë¼ëŠ” ë‹¨ì¼ jobì„ êµ¬ì„±
    build:
        # jobì´ ì‹¤í•¼ë  í™˜ê²½ - ìµœì‹  macOS
        runs-on: macos-latest
        
        # stepì€ jobì—ì„œ ì‹¤í–‰í•  ì¼ë ¨ì˜ ì‘ì—…ì„ ë‚˜íƒ€ëƒ„
        steps:
        # uses í‚¤ì›Œë“œë¥¼ í†µí•´ Github Actionì—ì„œ ê¸°ë³¸ìœ¼ë¡œ ì œê³µí•˜ëŠ” ì•¡ì…˜ ì‚¬ìš© ê°€ëŠ¥
        uses: actions/checkout@v4
        
        # shellì„ ì´ìš©í•´ ì¼ë ¨ì˜ ëª…ë ¹ì–´ë¥¼ ì‹¤í–‰
        - name: Start XCode Build ğŸ› ï¸
          run: |
            xcodebuild clean test -project Demo.xcodeproj -scheme Demo -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'
